"use client";
import {useEffect} from "react";
import {usePathname} from "next/navigation";
import type {AnalyticsEvent,VisitKind} from "@/lib/analytics";

const EVER_KEY="sns-hub-ever-visited-v1",SESSION_KEY="sns-hub-session-seen-v1";
function privacyOptOut(){const nav=navigator as Navigator&{globalPrivacyControl?:boolean};return nav.globalPrivacyControl===true||navigator.doNotTrack==="1"}
function visitKind():VisitKind{try{if(sessionStorage.getItem(SESSION_KEY)==="1")return "same-session";const returning=localStorage.getItem(EVER_KEY)==="1";sessionStorage.setItem(SESSION_KEY,"1");localStorage.setItem(EVER_KEY,"1");return returning?"returning":"first"}catch{return "unknown"}}
function send(event:AnalyticsEvent){void fetch("/_events",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",keepalive:true,body:JSON.stringify(event)}).catch(()=>{})}
function stableSegment(path:string,prefix:string){const match=path.match(new RegExp(`^/${prefix}/([a-z0-9][a-z0-9-]*)/?$`));return match?.[1]}
export function AnalyticsTracker(){const pathname=usePathname();useEffect(()=>{if(!pathname||privacyOptOut())return;send({schemaVersion:1,type:"page_view",path:pathname,occurredAt:new Date().toISOString(),visitKind:visitKind()})},[pathname]);useEffect(()=>{if(privacyOptOut())return;const handler=(event:MouseEvent)=>{const anchor=event.target instanceof Element?event.target.closest<HTMLAnchorElement>("a[href]"):null;if(!anchor)return;let destination:URL;try{destination=new URL(anchor.href,window.location.origin)}catch{return}if(destination.origin!==window.location.origin)return;const path=window.location.pathname,occurredAt=new Date().toISOString(),problem=stableSegment(destination.pathname,"problem"),category=stableSegment(destination.pathname,"category");if(problem)send({schemaVersion:1,type:"navigation",path,occurredAt,targetKind:"problem",targetId:problem});else if(category)send({schemaVersion:1,type:"navigation",path,occurredAt,targetKind:"category",targetId:category});else{const productSlug=stableSegment(path,"p"),targetProductSlug=stableSegment(destination.pathname,"p");if(productSlug&&targetProductSlug&&productSlug!==targetProductSlug)send({schemaVersion:1,type:"alternative_click",path,occurredAt,productSlug,targetProductSlug})}};document.addEventListener("click",handler,{capture:true});return()=>document.removeEventListener("click",handler,{capture:true})},[]);return null}
