import fs from "node:fs";import path from "node:path";import Ajv from "ajv";import addFormats from "ajv-formats";
import {ageDays,contentVersion,mergeCanonical,products,PRODUCT_STALE_DAYS,ROUTE_FRESH_DAYS,type Product} from "../lib/hub";
const root=process.cwd(), productDir=path.join(root,"data","products");
function validate(){const ajv=new Ajv({allErrors:true,strict:false});addFormats(ajv);const schema=JSON.parse(fs.readFileSync(path.join(root,"schemas/product.schema.json"),"utf8"));const check=ajv.compile(schema);const cats=new Set(JSON.parse(fs.readFileSync(path.join(root,"data/categories.json"),"utf8")).map((x:{id:string})=>x.id));const probs=new Set(JSON.parse(fs.readFileSync(path.join(root,"data/problem-tags.json"),"utf8")).map((x:{id:string})=>x.id));const ps=products(),ids=new Set<string>(),slugs=new Set<string>(),errors:string[]=[];
for(const p of ps){if(!check(p))errors.push(`${p.productId}: ${ajv.errorsText(check.errors)}`);if(ids.has(p.productId))errors.push(`duplicate productId ${p.productId}`);if(slugs.has(p.slug))errors.push(`duplicate slug ${p.slug}`);ids.add(p.productId);slugs.add(p.slug);for(const x of p.categoryIds)if(!cats.has(x))errors.push(`${p.productId}: unknown category ${x}`);for(const x of p.problemTagIds)if(!probs.has(x))errors.push(`${p.productId}: unknown problem ${x}`);if(p.pricing.display&&!p.pricing.verifiedAt)errors.push(`${p.productId}: exact price needs verifiedAt`);for(const r of p.routes)if(r.status==="ACTIVE"&&(!r.url||!r.destinationProductMatch))errors.push(`${p.productId}: invalid ACTIVE route`);for(const a of p.alternatives)if(!ps.some(x=>x.productId===a.productId)||a.productId===p.productId)errors.push(`${p.productId}: invalid alternative ${a.productId}`)}
if(errors.length){console.error(errors.join("\n"));process.exit(1)}console.log(`validated ${ps.length} products; contentVersion=${contentVersion()}`)}
function freshness(){let sp=0,sr=0;for(const p of products()){const a=ageDays(p.freshness.lastProductVerifiedAt);if(a===null||a>PRODUCT_STALE_DAYS){sp++;console.log("STALE_PRODUCT",p.productId,a)}for(const r of p.routes){const d=ageDays(r.verifiedAt);if(r.status==="ACTIVE"&&(d===null||d>ROUTE_FRESH_DAYS)){sr++;console.log("STALE_ROUTE",p.productId,r.routeId,d)}}}console.log({staleProducts:sp,staleActiveRoutes:sr})}
function upsert(file:string){const incoming=JSON.parse(fs.readFileSync(file,"utf8")) as Product;if(!/^[a-z0-9][a-z0-9-]*$/.test(incoming.productId))throw new Error("invalid productId");const target=path.join(productDir,`${incoming.productId}.json`),existing=fs.existsSync(target)?JSON.parse(fs.readFileSync(target,"utf8")) as Product:null,merged=mergeCanonical(existing,incoming);fs.writeFileSync(target,JSON.stringify(merged,null,2)+"\n");console.log(existing?"updated":"created",incoming.productId)}
function social(id:string,platform:string,postId:string,url:string,date=new Date().toISOString()){if(!["x","instagram"].includes(platform)||!url.startsWith("https://"))throw new Error("invalid social backlink");const f=path.join(productDir,`${id}.json`);const p=JSON.parse(fs.readFileSync(f,"utf8")) as Product;p.social=[...new Map([...p.social,{platform:platform as "x"|"instagram",postId,url,publishedAt:date}].map(x=>[`${x.platform}:${x.postId}`,x])).values()];p.publication.updatedAt=new Date().toISOString();fs.writeFileSync(f,JSON.stringify(p,null,2)+"\n");console.log("attached",platform,postId)}
const [cmd,...args]=process.argv.slice(2);if(cmd==="validate")validate();else if(cmd==="freshness")freshness();else if(cmd==="manifest")console.log(contentVersion());else if(cmd==="upsert"&&args[0])upsert(args[0]);else if(cmd==="social"&&args.length>=4)social(args[0],args[1],args[2],args[3],args[4]);else{console.error("hub.ts validate|freshness|manifest|upsert <file>|social <id> <platform> <postId> <url> [date]");process.exit(2)}
