import fs from "node:fs";
import path from "node:path";
import Ajv, { type ValidateFunction } from "ajv";
import addFormats from "ajv-formats";
import {ageDays,attachSocialBacklink,isHttpsUrl,manifest,mergeCanonical,PRODUCT_STALE_DAYS,ROUTE_FRESH_DAYS,type Product,type SocialBacklink,type Taxonomy} from "../lib/hub";

const root=process.cwd(),productDir=path.join(root,"data","products");
const ajv=new Ajv({allErrors:true,strict:false});addFormats(ajv);
const schema=JSON.parse(fs.readFileSync(path.join(root,"schemas/product.schema.json"),"utf8"));
const check:ValidateFunction=ajv.compile(schema);
type RecordOnDisk={file:string;product:unknown};
const readJson=(file:string)=>JSON.parse(fs.readFileSync(file,"utf8")) as unknown;
const loadRecords=():RecordOnDisk[]=>fs.readdirSync(productDir).filter(x=>x.endsWith(".json")).sort().map(file=>({file,product:readJson(path.join(productDir,file))}));
const loadTaxonomy=(name:string)=>JSON.parse(fs.readFileSync(path.join(root,"data",name),"utf8")) as Taxonomy[];
function taxonomyErrors(items:Taxonomy[],label:string){const errors:string[]=[],ids=new Set<string>(),slugs=new Set<string>();for(const x of items){if(!/^[a-z0-9][a-z0-9-]*$/.test(x.id))errors.push(`${label}: invalid id ${x.id}`);if(!/^[a-z0-9][a-z0-9-]*$/.test(x.slug))errors.push(`${label}: invalid slug ${x.slug}`);if(!x.label?.trim()||!x.description?.trim())errors.push(`${label}: ${x.id} needs label/description`);if(ids.has(x.id))errors.push(`${label}: duplicate id ${x.id}`);ids.add(x.id);if(slugs.has(x.slug))errors.push(`${label}: duplicate slug ${x.slug}`);slugs.add(x.slug)}return errors}
function future(value:string|null|undefined,now:Date){if(!value)return false;const d=new Date(value);return !Number.isNaN(d.valueOf())&&d.valueOf()>now.valueOf()+10*60_000}
function validationErrors(records=loadRecords(),now=new Date()){const cats=loadTaxonomy("categories.json"),probs=loadTaxonomy("problem-tags.json"),catIds=new Set(cats.map(x=>x.id)),probIds=new Set(probs.map(x=>x.id)),errors=[...taxonomyErrors(cats,"category"),...taxonomyErrors(probs,"problem")],valid:{file:string;product:Product}[]=[];for(const record of records){if(!check(record.product)){errors.push(`${record.file}: ${ajv.errorsText(check.errors)}`);continue}valid.push({file:record.file,product:record.product as Product})}const ids=new Set<string>(),slugs=new Set<string>(),allIds=new Set(valid.map(x=>x.product.productId));for(const {file,product:p} of valid){if(file!==`${p.productId}.json`)errors.push(`${file}: filename must match productId ${p.productId}`);if(ids.has(p.productId))errors.push(`duplicate productId ${p.productId}`);ids.add(p.productId);if(slugs.has(p.slug))errors.push(`duplicate slug ${p.slug}`);slugs.add(p.slug);for(const x of p.categoryIds)if(!catIds.has(x))errors.push(`${p.productId}: unknown category ${x}`);for(const x of p.problemTagIds)if(!probIds.has(x))errors.push(`${p.productId}: unknown problem ${x}`);if(p.pricing.display&&!p.pricing.verifiedAt)errors.push(`${p.productId}: exact price needs verifiedAt`);if(future(p.pricing.verifiedAt,now)||future(p.freshness.lastProductVerifiedAt,now)||future(p.freshness.lastPriceVerifiedAt,now)||future(p.freshness.lastAffiliateRouteVerifiedAt,now)||future(p.publication.firstPublishedAt,now)||future(p.publication.updatedAt,now))errors.push(`${p.productId}: future-dated verification/publication timestamp`);const routeIds=new Set<string>();for(const r of p.routes){if(routeIds.has(r.routeId))errors.push(`${p.productId}: duplicate routeId ${r.routeId}`);routeIds.add(r.routeId);if(r.status==="ACTIVE"&&(!isHttpsUrl(r.url)||!r.destinationProductMatch))errors.push(`${p.productId}: invalid ACTIVE route ${r.routeId}`);if(r.routeType==="affiliate"&&!r.disclosureRequired)errors.push(`${p.productId}: affiliate route ${r.routeId} must require disclosure`);if(["unavailable","discontinued"].includes(p.availability)&&r.status==="ACTIVE")errors.push(`${p.productId}: unavailable product cannot keep ACTIVE route ${r.routeId}`);if(future(r.verifiedAt,now))errors.push(`${p.productId}: future route verification ${r.routeId}`)}const socialKeys=new Set<string>();for(const s of p.social){const k=`${s.platform}:${s.postId}`;if(socialKeys.has(k))errors.push(`${p.productId}: duplicate social backlink ${k}`);socialKeys.add(k);if(future(s.publishedAt,now))errors.push(`${p.productId}: future social timestamp ${k}`)}for(const a of p.alternatives){if(!allIds.has(a.productId)||a.productId===p.productId)errors.push(`${p.productId}: invalid alternative ${a.productId}`);if(future(a.verifiedAt,now))errors.push(`${p.productId}: future alternative verification ${a.productId}`)}}return errors}
function assertValid(records=loadRecords()){const errors=validationErrors(records);if(errors.length)throw new Error(errors.join("\n"))}
function validate(){try{assertValid();console.log(`validated ${loadRecords().length} products; contentVersion=${manifest().contentVersion}`)}catch(error){console.error(error instanceof Error?error.message:error);process.exit(1)}}
function freshness(){let sp=0,sr=0;for(const {product:raw} of loadRecords()){if(!check(raw))continue;const p=raw as Product,a=ageDays(p.freshness.lastProductVerifiedAt);if(a===null||a<0||a>PRODUCT_STALE_DAYS){sp++;console.log(a!==null&&a<0?"FUTURE_PRODUCT":"STALE_PRODUCT",p.productId,a)}for(const r of p.routes){const d=ageDays(r.verifiedAt);if(r.status==="ACTIVE"&&(d===null||d<0||d>ROUTE_FRESH_DAYS)){sr++;console.log(d!==null&&d<0?"FUTURE_ROUTE":"STALE_ROUTE",p.productId,r.routeId,d)}}}console.log({staleProducts:sp,staleActiveRoutes:sr})}
function writeProduct(p:Product){const target=path.join(productDir,`${p.productId}.json`),tmp=`${target}.${process.pid}.${Date.now()}.tmp`;fs.writeFileSync(tmp,JSON.stringify(p,null,2)+"\n");fs.renameSync(tmp,target)}
function upsert(file:string){const incomingRaw=readJson(file);if(!check(incomingRaw))throw new Error(`incoming product: ${ajv.errorsText(check.errors)}`);const incoming=incomingRaw as Product,records=loadRecords(),existingRecord=records.find(x=>(x.product as {productId?:string})?.productId===incoming.productId),existing=existingRecord?.product as Product|undefined,merged=mergeCanonical(existing??null,incoming),next=records.filter(x=>(x.product as {productId?:string})?.productId!==incoming.productId);next.push({file:`${incoming.productId}.json`,product:merged});assertValid(next);writeProduct(merged);console.log(existing?"updated":"created",incoming.productId)}
function social(id:string,platform:string,postId:string,url:string,date=new Date().toISOString()){if(!["x","instagram"].includes(platform)||!postId.trim()||!isHttpsUrl(url)||Number.isNaN(new Date(date).valueOf())||future(date,new Date()))throw new Error("invalid social backlink");const target=path.join(productDir,`${id}.json`);if(!fs.existsSync(target))throw new Error(`unknown productId ${id}`);const p=readJson(target) as Product;if(p.publication.status==="staged")throw new Error("cannot attach a published social backlink to a staged product before HUB_READY");const backlink:SocialBacklink={platform:platform as "x"|"instagram",postId,url,publishedAt:date},result=attachSocialBacklink(p,backlink);if(!result.changed){console.log("unchanged",platform,postId);return}const records=loadRecords().filter(x=>(x.product as {productId?:string})?.productId!==id);records.push({file:`${id}.json`,product:result.product});assertValid(records);writeProduct(result.product);console.log("attached",platform,postId,result.product.publication.status)}
const [cmd,...args]=process.argv.slice(2);try{if(cmd==="validate")validate();else if(cmd==="freshness")freshness();else if(cmd==="manifest")console.log(JSON.stringify(manifest(),null,2));else if(cmd==="upsert"&&args[0])upsert(args[0]);else if(cmd==="social"&&args.length>=4)social(args[0],args[1],args[2],args[3],args[4]);else{console.error("hub.ts validate|freshness|manifest|upsert <file>|social <id> <platform> <postId> <url> [date]");process.exit(2)}}catch(error){console.error(error instanceof Error?error.message:error);process.exit(1)}
